# Generated by Django 4.2.5 on 2024-10-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.CharField(help_text='El código se autogenera al guardar la cuenta', max_length=50, verbose_name='Código'),
        ),
    ]
